Categories endpoint
p-zielinski/voucherify-js-sdk pull request #8
Opened 2023-08-28 07:33 UTC by p-zielinski

2023-09-06 12:50 UTC, marcin-slezak requested changes
Why did we start from branch `types-002`? It could be just minor to the current major version.

2023-09-06 12:50 UTC, marcin-slezak commented on .changeset/comics-voucherify-two.md
> +To run tests you need to copy packages/sdk/.env.example to packages/sdk/.env and fill the file with your credentials.
Duplicated update about .env for a tests

2023-09-06 15:08 UTC, p-zielinski commented on packages/sdk/README.md
> +- [Add Voucher to Campaign](#add-voucher-to-campaign)
![Screenshot 2023-09-06 at 17 07 26](https://github.com/p-zielinski/voucherify-js-sdk/assets/82354717/11177be1-e0c6-4571-bf93-e200e150894c)

This is a list of `Categories API`
https://docs.voucherify.io/reference/category-object

2023-09-13 12:53 UTC, marcin-slezak requested changes

2023-09-13 12:53 UTC, marcin-slezak commented on .changeset/comics-voucherify-two.md
> +  - Added support for new endpoints: `/campaigns/campaignId/enable`,`/campaigns/campaignId/disable`, `/categories` and `/categories/id` [(examples of usage available in readme.md)](..%2F..%2Fpackages
When you list using URI, you need to provide an HTTP method to be unequivocal

2023-09-13 12:54 UTC, marcin-slezak requested changes
maybe some tests?

2023-09-13 18:20 UTC, p-zielinski commented on packages/sdk/README.md
> +- [Add Voucher to Campaign](#add-voucher-to-campaign)
🤦 you are right

2023-09-14 11:28 UTC, closed without merging